spring:
  application:
    name: admin-client-b
  boot:
    admin:
      client:
        url: http://localhost:7070

server:
  port: 8081

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
