spring:
  application:
    name: admin-client-a
  boot:
    admin:
      client:
        url: http://localhost:7070
        instance:
          metadata:
            user:
              name: admin
              password: adminadmin

server:
  port: 8082

logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file: /usr/local/tomcat/project/spring-boot-admin-without-eureka/data/logs/admin-client-a.log

management:
  endpoints:
    web:
      exposure:
        include: '*'